server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3308/identity_service}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "Xt63ldcIkFha1Vyp4P4iOQPZ9uhPfzt+pEd8yn5MXlJiT0VS/hzyAq4FRgA6dRXp"
  valid-duration: 3600 # in seconds
  refreshable-duration: 360000 # in seconds