server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3308/identity_service"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "Xt63ldcIkFha1Vyp4P4iOQPZ9uhPfzt+pEd8yn5MXlJiT0VS/hzyAq4FRgA6dRXp"